# variables that Hugo converts automatically
baseURL = 'https://mms.org.mt/' #site.BaseURL
title = 'Malta Mathematical Society' #site.Title
copyright = '© 2026 Malta Mathematical Society' #site.Copyright

defaultContentLanguage = 'en' 
defaultContentLanguageInSubDir = true

# Custom site-wide variables belong here!
[params]
  email = 'maltamathematicalsociety@gmail.com' #site.Params.email
  #decide on icon file here to be used in baseof.html
  browserIcon = "logo-only-color-borderless.png" #used in badeof.html
  homeIcon = "logo-primary-color-light-background-borderless.svg" #used in header.html


#for bilingualism rather than coding two websites we will use the inbuilt transaltion i18n folder,
# which exists to translate static UI strings (like "Read More", "Subscribe", navigation menus, and footer text) 
# using dictionary files (i18n/en.toml and i18n/mt.toml) rather than hardcoding text in HTML templates.

#https://gohugo.io/configuration/languages/
[languages]
  [languages.en]
    locale = 'en' #site.Locale
    label = 'English'
    weight = 1
  
  [languages.mt]
    locale = 'mt'
    label = 'Malti'
    weight = 2

[languages.mt.permalinks.section] #each arcive ovewiew will have translated URL
  comics = '/il-komiks/'
  events = '/attivitajiet/'
  newsletters = '/aħbarijiet/'
  
[languages.mt.permalinks.page] #each archive post will have a translated URL
  comics = '/il-komiks/:slug/'
  events = '/attivitajiet/:slug/'
  newsletters = '/aħbarijiet/:slug/'


#all hardcoded referenced links for the Mailing List here
[params.mailerlite]
  action_url = "https://assets.mailerlite.com/jsonp/2669609/forms/199945518538819358/subscribe"

[outputFormats]
  [outputFormats.Email]
    mediaType = "application/json"
    baseName = "email"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"] 

# Only generate email.json inside comics, newsletters, and events
[[cascade]]
  outputs = ["HTML", "Email"]
  [cascade.target]
    path = "/{comics,newsletters,events}/**"