DRY_RUN = True

import json
import os
import glob
import requests
from pathlib import Path

# ==========================================
# 1. CONFIGURATION & ENVIRONMENT
# ==========================================
SENDER_EMAIL = "Malta Mathematical Society"
SENDER_NAME = "maltamathematicalsociety@gmail.com"

MAILERLITE_API_KEY = os.getenv("MAILERLITE_API_KEY", "your_mailerlite_api_key")
MAILERLITE_API_URL = "https://connect.mailerlite.com/api/campaigns"

# Relative project paths
BASE_DIR = Path(__file__).resolve().parent
POST_HISTORY_PATH = BASE_DIR / "sent_posts.json"
PUBLIC_DIR = BASE_DIR / "public"

# Map (Language, Category) to MailerLite Group IDs
SEGMENT_MAP = {
    "comics": {"en": "200021722566493719","mt": "200021561893193536",},
    "events": {"en": "200420005459789243","mt": "200420047752005247",},
    "newsletters": {"en": "200419938428520315","mt": "200419980685084578",},
}

# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
def load_post_history() -> set:
    """Loads recorded GUIDs from sent_posts.json."""
    if os.path.exists(POST_HISTORY_PATH):
        with open(POST_HISTORY_PATH, "r", encoding="utf-8") as f:
            try:
                return set(json.load(f))
            except json.JSONDecodeError:
                return set()
    return set()

def save_post_history(sent_guids: set):
    """Persists sent GUIDs back to sent_posts.json."""
    POST_HISTORY_PATH.write_text(json.dumps(sorted(list(sent_guids)), indent=2), encoding="utf-8")

def send_to_mailerlite(title: str, inlined_html: str, target_group_id: str,) -> bool:
    """Creates and dispatches a campaign in MailerLite via API v3."""
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {MAILERLITE_API_KEY}"
    }

    payload = {
        "name": f"Auto-Dispatch: {title}",
        "type": "regular",
        "emails": [
            {
                "subject": title,
                "from_name": SENDER_NAME,
                "from": SENDER_EMAIL,
                "content": inlined_html
            }
        ],
        "groups": [target_group_id]
    }

    response = requests.post(MAILERLITE_API_URL, headers=headers, json=payload)

    if response.status_code in (200, 201):
        print(f"Successfully created campaign for: '{title}' (Group: {target_group_id})")
        return True
    else:
        print(f"MailerLite API Error [{response.status_code}]: {response.text}")
        return False

# ==========================================
# 3. MAIN EXECUTION PIPELINE
# ==========================================
def main():
    #Discovers all generated JSON files automatically with zero hardcoding
    post_history = load_post_history()#Load previously sent post GUIDs from post_history.json using helper function

    # Search for all email.json files generated by Hugo inside public/
    json_files = glob.glob(str(PUBLIC_DIR / "**" / "email.json"), recursive=True)
    print(f"Found {len(json_files)} email payload files in build output.")
     
    for json_path in json_files:
        #load json file
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        guid = data["guid"]
        title = data["title"]
        lang = data["lang"]
        category = data["category"]
        email_html = data["html_content"]

        # 1. Skip if post is not new
        if guid in post_history: #sendt post is the json history looaded
            print(f":3 Skipping already sent post: {title} ({guid})")
            continue

        # 1. Skip if send_mail=false
        if not data.get("send_mail", True):
            print(f":3 Skipping post with send_mail=false: {title} ({guid})")
            continue
        
        # 2. Determine target MailerLite group
        target_group = SEGMENT_MAP.get(category.lower(), {}).get(lang.lower())
        if not target_group:
            print(f"❌ Hey! No group mapping found for lang='{lang}' and category='{category}'. Skipping '{title}'. Emails should only be generating for allowed categories, as defined in hugo.toml!")
            continue

        print(f"Processing new post: '{title}' [{lang}/{category}]")

        # 3. Dispatch via MailerLite API OR the dry run kicks in
        if DRY_RUN:
            # Create a safe filename from the post title
            safe_filename = "".join(c if c.isalnum() else "_" for c in title).lower()
            preview_filename = f"preview_{lang}_{safe_filename}.html"
                
            with open(preview_filename, "w", encoding="utf-8") as f:
                f.write(email_html)
                    
            print(f" [DRY RUN SUCCESS] Validated '{title}' [{lang}/{category}]")
            print(f"   > Would dispatch to MailerLite Group ID: {target_group}")
            print(f"   > Saved email preview to: {preview_filename}\n")
            continue  # Do NOT call MailerLite or write to post_history.json

        success = send_to_mailerlite(title, email_html, target_group)

        # 5. Update tracking store upon successful API response
        if success:
            post_history.add(guid) #the sendt post is now old
            save_post_history(post_history) 

if __name__ == "__main__":
    main()